name: Raffle_box 
main: Raf\Main
version: 1.0.5
api: 
- 3.0.0
- 4.0.0
load: POSTWORLD
author: MengBao
commands:
 R:
  description: "抽奖箱主指令"
  usage: "/R help"
  permission: Raffle.command.R
permissions:
 Raffle.command.R:
  default: op
  description: "这代表只有OP有这个权限"
  